### ISSUE TITLE
Will the Mod support for 1.19.2 as well?

### ISSUE THREAD

**Issue by HUYBUSSIN** [txnimc/ImmersiveMessages#2]
Hello, my apologies this is not an issue because there is currently no official way to post directly on the homepage. I wonder if version 1.19.2 will be supported. Because I see a lot of famous Modpacks and even my developing Modpack is still on 1.19.2. If possible, I hope you can support this version because honestly this is an indispensable tool for Modpack developers and I personally love it. Thank you

**Comment by nthxny** [comment]
Not unless Connector gets a backport.
